### ISSUE TITLE
Implement messages.getPeerSettings

### ISSUE THREAD

**Issue by aykutalparslan** [aykutalparslan/Ferrite#171]
Get peer settings

> [peerSettings](https://core.telegram.org/constructor/peerSettings)[#](https://core.telegram.org/type/%23)733f2961 flags:# report_spam:flags.0?true add_contact:flags.1?true block_contact:flags.2?true share_contact:flags.3?true need_contacts_exception:flags.4?true report_geo:flags.5?true autoarchived:flags.7?true invite_members:flags.8?true geo_distance:flags.6?[int](https://core.telegram.org/type/int) = [PeerSettings](https://core.telegram.org/type/PeerSettings);
> ---functions---
> [messages.getPeerSettings](https://core.telegram.org/method/messages.getPeerSettings)#3672e09c peer:[InputPeer](https://core.telegram.org/type/InputPeer) = [PeerSettings](https://core.telegram.org/type/PeerSettings)[](https://core.telegram.org/method/messages.getPeerSettings#parameters);

**Comment by junko2013** [comment]
收到。。
