### ISSUE TITLE
Socket not work

### ISSUE THREAD

**Issue by AliKhadivi** [aykutalparslan/ferrite#427]
Hi
Socket not work
https://drive.google.com/file/d/1CEuRLJE2-ovsKszX_eRiCJHBMUfoWmBx/view?usp=sharing
screenshot ↑

**Comment by aykutalparslan** [comment]
Folowing commits add WebSocket Support 2f6b4ceb112b025de2e1cf4049cb4d18c77acb9c 4a85d442ea6ee8d98c8fac731bc7e892cfb0be9d 5b4b9223788639906ecaf7496c40c1568e3e27f0

**Comment by AliKhadivi** [comment]
#456
#458
Fixed
