### ISSUE TITLE
How to a build APK?

### ISSUE THREAD

**Issue by terexdev** [aykutalparslan/Ferrite#441]

**Comment by aykutalparslan** [comment]
You would need to clone https://github.com/aykutalparslan/Telegram and build it as per the original build instructions.

**Comment by terexdev** [comment]
> You would need to clone https://github.com/aykutalparslan/Telegram and build it as per the original build instructions.

how to a get RELEASE_KEY_PASSWORD, RELEASE_KEY_ALIAS, RELEASE_STORE_PASSWORD ?

**Comment by aykutalparslan** [comment]
You need to create your own keystore. You can do so using the instructions [here](https://stackoverflow.com/questions/3997748/how-can-i-create-a-keystore).
