### ISSUE TITLE
how to start on wds on ubuntu linux

### ISSUE THREAD

**Issue by terexdev** [aykutalparslan/Ferrite#442]

**Comment by aykutalparslan** [comment]
To start the server you need to at least start Redis, Cassandra, Minio, ElasticSearch Instances and update the [Program.cs ](https://github.com/aykutalparslan/Ferrite/blob/master/Ferrite/Program.cs)accordingly. 

However at this early stage of development anything other than the dev environment wouldn't make much sense. I myself am using JetBrains Rider but you can use Microsoft Visual Studio to debug.
