### ISSUE TITLE
Thank you for doing an amazing thing.

### ISSUE THREAD

**Issue by mailes** [aykutalparslan/Ferrite#451]
Thank you for doing an amazing thing. I will always pay attention to the progress of this project. If necessary, I can give appropriate help. I am an Android and iOS development engineer

**Comment by mailes** [comment]
If you see this message, please close it.

**Comment by aykutalparslan** [comment]
Thank you for your offer. At the moment the project needs a little more work to be done before it's time to modify the mobile apps however.
