### ISSUE TITLE
Add " telegram-server" tag to this repo

### ISSUE THREAD

**Issue by bob27aggiustatutto** [aykutalparslan/Ferrite#466]
Those are the current tags
![image](https://user-images.githubusercontent.com/120955097/224478236-fbdef81a-8637-4385-92b1-464d393a9e67.png)

I've noticed that you will be far more reachable if you add the "telegram-server" tag by Google search.

Thank you and keep up with the good work!

**Comment by junko2013** [comment]
收到。。
